### ISSUE TITLE
[Rust Activate Mexico City 2017] Difusión

### ISSUE THREAD

**Issue by sebasmagri** [rustmx/team#3]
La estrategia de difusión se daría en los siguientes frentes:

- Universidades / escuelas
  - UNAM
  - ITESM
  - ... (podemos conseguir contactos con otras escuelas?)
- Empresas / Instituciones
  - Nearsoft
  - SocialTIC
  - [Rancho Electrónico](http://ranchoelectronico.org/)
  - Software Gurú
  - [Women Who Code DF](https://www.womenwhocode.com/df)
  - Laboratoria
  - Centro de Cultura Digital
  - EpicQueen
  - ...
- Meetups
  - Los de RustMX
  - Todos los demás que lo permitan en sus anuncios parroquiales

La estrategia de difusión debería estar orientada principalmente a hacer que el evento sea sumamente inclusivo, con participación de todos los segmentos y comunidades de la industria. La audiencia objetivo es de 60 participantes.

Tareas:
 - [x] Formatos de contacto #7 
 - [ ] Posters, share images para redes sociales, banners para perfiles de redes sociales #4
 - [x] Landing page del evento 
 - [ ] Texto para publicaciones en redes sociales
 - [ ] Cronograma de publicaciones en redes sociales
 - [ ] Flyers del evento
 - [ ] Contactar meetups de CDMX #5

**Comment by yulireyji** [comment]
Algunas tareas ya se encuentran realizadas, seria bueno marcarlas, en tanto a difusión con redes sociales ¿ya se cuenta con una lista de comunidades de apoyo? 

Me surge la duda... Hasta el momento se contaba con el apoyo de SocialTIC, Y Nearsoft que quedan como colaboradores/sponsor del evento, pero las demás comunidades como quedan, en dado caso de solicitar el apoyo.

**Comment by sebasmagri** [comment]
@yulireyji hola!

Acabé de marcar como hecha la tarea del formato de contacto.

Del resto de tareas, hay alguna que ya podamos marcar como lista? Creo que el landing page todavía tiene algunos temas pendientes que estamos viendo con @Heeled-Jim.

Sobre la duda del apoyo, estamos considerando temas distintos. Estas empresas y organizaciones se van a estar contactando solo para fines de difusión, y en paralelo con todo el esfuerzo de difusión normal, en el sentido de hacerles una invitación más formal a participar del evento. La finalidad es que podamos enfocarnos en organizaciones que estén enfocadas en la inclusión en la tecnología y en comunidades con baja representación en la industria. Igualmente, de acuerdo con el formato de contacto, dejamos la puerta abierta para recibir cualquier colaboración que puedan ofrecer, la cual vamos a evaluar en caso de que se dé.

La colaboración que nos van a estar prestando SocialTIC, Nearsoft y Software Gurú ya está acordada y encaminada de manera independiente a este esfuerzo de difusión.

**Comment by Heeled-Jim** [comment]
Hola mis estimados @yulireyji y @sebasmagri 

Ya tenemos contacto y correos con gente de la UNAM, el ITESM y agreguen al ITIZ también porfavor...

Quiero invitar a la comunidad de Wikimedia MX para ver si se puede armar una actividad paralela como un editatón de temas de computación y programación ¿que opinan? avísenme para contactar a le gente de Wikimedia MX porfavor...
